### ISSUE TITLE
More options than /players & /mixer?

### ISSUE THREAD

**Issue by KonstantinEger** [legrosmanu/rest-api-squeezebox#1]
I want to use this API for my own project but i think it has not enough functionality. Is there a way we could implement options for changing the playlist for example?

**Comment by legrosmanu** [comment]
Yes, it has not enough functionality. So thank you for your message, it give me desire to do more.
I'll check if I could propose to change the playlist on the PATCH /players/{uuid}.

**Comment by legrosmanu** [comment]
I don't have a lot of time actually. I pushed patch /players/{uuid}/playlist and DELETE /players/{uuid}/playlist. It's just a beginning ;-)
